# ----- Github Action -----
name: Rrea-client

# 実行のタイミング
on: workflow_dispatch
# pushで実行したい場合は、↓を使う
#   push:
#     branches: [ "master" ]

# 実行の流れ
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 実行開始
      - name: start deploy
        run: echo Start deploy!

    # SSHでサーバー接続
      - name: access server
            uses: appleboy/ssh-action@master
            with:
              host: ${{ secrets.TENCENT_UBUNTU_HOST }}
              username: ${{ secrets.TENCENT_UBUNTU_USERNAME }}
              password: ${{ secrets.TENCENT_UBUNTU_PASSWORD }}
              port: ${{ secrets.TENCENT_UBUNTU_PORT }}
              script: |
                sudo su root
                echo "fuck you"